### ISSUE TITLE
распознавание: выбор библиотеки

### ISSUE THREAD

**Issue by ioannnikulin** [kruglm/Predprofil#3]
составить список библиотек распознавания и найти для каждой простейший пример (отличить 1 от 2)

**Comment by kruglm** [comment]
Computer Vision от Microsoft:
Ссылка на продукт: http://tiny.cc/g2dtkz
Ссылка на документацию про проект: http://tiny.cc/d4dtkz

**Comment by ioannnikulin** [comment]
@kruglm  это хорошо) давай только это будут не только ссылки на продукт, а сразу уж ссылки на руководства по быстрому написанию простейших примеров) а ещё лучше "я запустил, вот скриншоты"

**Comment by kruglm** [comment]
http://tiny.cc/mrftkz Еще одно обучение как это делать но уже на питоне и с другими библиотеками и без каких либо скринов от меня

**Comment by kruglm** [comment]
Сбор всех библиотек (если что то редачьте этот комент):
-Keras(Python)
-Pytorch(C++; Python)
-Computer Vision (C# and smth else)
-TensorFlow(Python; C++; Java)
-Alturos.Yolo(С# and smth else) https://github.com/AlturosDestinations/Alturos.Yolo

**Comment by kruglm** [comment]
С библиотекой наверное все:
Все сделано на Alturos.Yolo 
С#
Код:
using Alturos.Yolo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace YoloTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect();
            using (var yoloWrapper = new YoloWrapper(config))
            {
                var items = yoloWrapper.Detect(@"C:\Chec\print.jpg");
                //items[0].Type -> "Person, Car, ..."
                //items[0].Confidence -> 0.0 (low) -> 1.0 (high)
                //items[0].X -> bounding box
                //items[0].Y -> bounding box
                //items[0].Width -> bounding box
                //items[0].Height -> bounding box
                foreach (var p in items)
                {
                    Console.WriteLine(p.Type);
                    Console.WriteLine(p.Confidence);
                }
            }
            Console.ReadKey();
        }
    }
}

Вывод:
batch = 1, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  13 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  14 conv    125       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 125 0.043 BF
  15 detection
mask_scale: Using default '1.000000'
Total BFLOPS 6.977
avg_outputs = 454208
Loading weights from .\yolov2-tiny-voc.weights...
 seen 32, trained: 2566 K-images (40 Kilo-batches_64)
Done! Loaded 16 layers from weights-file
 Not used AVX
 Not used FMA & AVX2
car
0,734520792961121

Картинка:
![print](https://user-images.githubusercontent.com/61741007/76012024-a29fd080-5f26-11ea-8f6d-93e8adcae3d9.jpg)

**Comment by ioannnikulin** [comment]
Ты мой кумир))
