### ISSUE TITLE
озвучка: найти озвучивальщика

### ISSUE THREAD

**Issue by ioannnikulin** [kruglm/Predprofil#4]
написать программу, которая подключается к какому-то сервису озвучки, передаёт ему текст, получает обратно аудиофайл

**Comment by kruglm** [comment]
Вот урок по С#( как я понимаю и все прогу пишем на нем ) как озвучивать текст с помощью обычных библиотек Visual Studio: http://tiny.cc/gdetkz
Правда еще не потестил с русским языком

**Comment by kruglm** [comment]
Вот пример консольного приложения на C#:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Speech.Synthesis;
using System.Text;
using System.Threading.Tasks;

namespace VoiceActing
{
    class Program
    {
        static void Main(string[] args)
        {
            SpeechSynthesizer synth = new SpeechSynthesizer();

            synth.SetOutputToDefaultAudioDevice();

            synth.Speak("Стол, стул, ежик, солнце, банка");

            Console.WriteLine();
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}
Библиотеки встроены в VS

Пример видео :https://www.youtube.com/watch?v=4zdmSVgtfkU
Скрины тут уже бесполезны

**Comment by ioannnikulin** [comment]
@kruglm  шикарно) запустить у себя пробовал?

**Comment by kruglm** [comment]
Да, запускал, всё работает

**Comment by ioannnikulin** [comment]
@kruglm герой!)
